version: '3.9'
services:
  frontend:
    build: app/front-end
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-front-end
  backend:
    container_name: app-back-end
    build: app/back-end
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-back-end
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASS=Password!2
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_NAME=PASTA_SO_TASTY
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: PASTA_SO_TASTY_DB
    platform: linux/x86_64
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Password!2
    restart: 'always'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
